name: Deploy to GAE

on: [ push,workflow_dispatch ]

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v1.0.0
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          deliverables: app.yaml
          version: v1

      - name: Test
        run: curl "${{ steps.deploy.outputs.url }}"
